version: '3'
services:
# clm
  clm:
    image: splunk/splunk:8.0
    ports:
      - "8001:8000"
      - "8002:8089"
      - "12011:22"
    volumes:
      - /docker/dockercompose/clm/etc:/opt/splunk/etc
      - /docker/dockercompose/clm/var:/opt/splunk/var
    hostname: clm
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=http://localhost/splunk.lic 
      - SPLUNK_PASSWORD=Splunk4sidetesting 
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - DEBUG=true
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - SPLUNK_SITE=site1
      - SPLUNK_ALL_SITES=site1,site2
      # - SPLUNK_SEARCH_FACTOR=2
      # - SPLUNK_REPLICATION_FACTOR=2
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_ORIGIN=2
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_TOTAL=3
      - SPLUNK_MULTISITE_SEARCH_FACTOR_ORIGIN=2
      - SPLUNK_MULTISITE_SEARCH_FACTOR_TOTAL=3
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_MULTISITE_MASTER_PORT=8089

  idx1:
    image: splunk/splunk:8.0
    ports:
      - "8011:8000"
    volumes:
      - /docker/dockercompose/idx1/etc:/opt/splunk/etc
      - /docker/dockercompose/idx1/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/db/

    hostname: idx1
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  
  idx2:
    image: splunk/splunk:8.0
    ports:
      - "8021:8000"
    volumes:
      - /docker/dockercompose/idx2/etc:/opt/splunk/etc
      - /docker/dockercompose/idx2/var:/opt/splunk/var
    hostname: idx2
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx3:
    image: splunk/splunk:8.0
    ports:
      - "8041:8000"
    volumes:
      - /docker/dockercompose/idx3/etc:/opt/splunk/etc
      - /docker/dockercompose/idx3/var:/opt/splunk/var
    hostname: idx3
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx4:
    image: splunk/splunk:8.0
    ports:
      - "8051:8000"
    volumes:
      - /docker/dockercompose/idx4/etc:/opt/splunk/etc
      - /docker/dockercompose/idx4/var:/opt/splunk/var
    hostname: idx4
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx5:
    image: splunk/splunk:8.0
    ports:
      - "8061:8000"
    volumes:
      - /docker/dockercompose/idx5/etc:/opt/splunk/etc
      - /docker/dockercompose/idx5/var:/opt/splunk/var
    hostname: idx5
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx6:
    image: splunk/splunk:8.0
    ports:
      - "8071:8000"
    volumes:
      - /docker/dockercompose/idx6/etc:/opt/splunk/etc
      - /docker/dockercompose/idx6/var:/opt/splunk/var
    hostname: idx6
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx7:
    image: splunk/splunk:8.0
    ports:
      - "8081:8000"
    volumes:
      - /docker/dockercompose/idx7/etc:/opt/splunk/etc
      - /docker/dockercompose/idx7/var:/opt/splunk/var
    hostname: idx7
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

  idx8:
    image: splunk/splunk:8.0
    ports:
      - "8091:8000"
    volumes:
      - /docker/dockercompose/idx8/etc:/opt/splunk/etc
      - /docker/dockercompose/idx8/var:/opt/splunk/var
    hostname: idx8
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=clm
      - SPLUNK_LICENSE_URI

# 
# /opt/splunk/bin/splunk edit cluster-config -mode master -multisite true -available_sites site1,site2 -site site1 -site_replication_factor origin:2,total:3 -site_search_factor origin:2,total:3 -auth admin:Splunk4sidetesting -secret mypass4splunk

# clm_1  | TASK [splunk_cluster_master : Set the multisite master] ************************
# clm_1  | fatal: [localhost]: FAILED! => {
# clm_1  |     "attempts": 50,
# clm_1  |     "changed": false,
# clm_1  |     "cmd": [
# clm_1  |         "/opt/splunk/bin/splunk",
# clm_1  |         "edit",
# clm_1  |         "cluster-config",
# clm_1  |         "-mode",
# clm_1  |         "master",
# clm_1  |         "-multisite",
# clm_1  |         "true",
# clm_1  |         "-available_sites",
# clm_1  |         "site1,site2",
# clm_1  |         "-site",
# clm_1  |         "site1",
# clm_1  |         "-site_replication_factor",
# clm_1  |         "origin:1,total:2",
# clm_1  |         "-site_search_factor",
# clm_1  |         "origin:1,total:2",
# clm_1  |         "-auth",
# clm_1  |         "admin:Splunk4sidetesting",
# clm_1  |         "-secret",
# clm_1  |         "mypass4splunk"
# clm_1  |     ],
# clm_1  |     "delta": "0:00:00.684481",
# clm_1  |     "end": "2019-12-05 14:11:23.512526",
# clm_1  |     "rc": 22,
# clm_1  |     "start": "2019-12-05 14:11:22.828045"
# clm_1  | }
# clm_1  |
# clm_1  | STDERR:
# clm_1  |
# clm_1  | Invalid site_replication_factor, Reason: total should be greater than or equal to replication_factor.
# clm_1  |
# clm_1  |
# clm_1  | MSG:
# clm_1  |