version: '3'
services:
  clm:
    image: splunk/splunk:8.0
    ports:
      - "8001:8000"
      - "8002:8089"
      - "12011:22"
    volumes:
      - /docker/dockercompose/clm/etc:/opt/splunk/etc
      - /docker/dockercompose/clm/var:/opt/splunk/var
      - /home/ubuntu/git/splunk-sitetest/docker-compose/scenarios/1site-32instances-sf4/default.yml:/tmp/defaults/default.yml
    hostname: clm
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_cluster_master
      - DEBUG=true
      - SPLUNK_INDEXER_URL=idx01,idx02,idx03,idx04,idx05,idx06,idx07,idx08
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - SPLUNK_IDXC_SEARCH_FACTOR=4
