 
idx01:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx01/etc:/opt/splunk/etc
      - /docker/dockercompose/idx01/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx01
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx02:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx02/etc:/opt/splunk/etc
      - /docker/dockercompose/idx02/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx02
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx03:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx03/etc:/opt/splunk/etc
      - /docker/dockercompose/idx03/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx03
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx04:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx04/etc:/opt/splunk/etc
      - /docker/dockercompose/idx04/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx04
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx05:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx05/etc:/opt/splunk/etc
      - /docker/dockercompose/idx05/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx05
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx06:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx06/etc:/opt/splunk/etc
      - /docker/dockercompose/idx06/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx06
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx07:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx07/etc:/opt/splunk/etc
      - /docker/dockercompose/idx07/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx07
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx08:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx08/etc:/opt/splunk/etc
      - /docker/dockercompose/idx08/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx08
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx09:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx09/etc:/opt/splunk/etc
      - /docker/dockercompose/idx09/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx09
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx10:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx10/etc:/opt/splunk/etc
      - /docker/dockercompose/idx10/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx10
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx11:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx11/etc:/opt/splunk/etc
      - /docker/dockercompose/idx11/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx11
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx12:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx12/etc:/opt/splunk/etc
      - /docker/dockercompose/idx12/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx12
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx13:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx13/etc:/opt/splunk/etc
      - /docker/dockercompose/idx13/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx13
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx14:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx14/etc:/opt/splunk/etc
      - /docker/dockercompose/idx14/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx14
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx15:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx15/etc:/opt/splunk/etc
      - /docker/dockercompose/idx15/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx15
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx16:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx16/etc:/opt/splunk/etc
      - /docker/dockercompose/idx16/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx16
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx17:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx17/etc:/opt/splunk/etc
      - /docker/dockercompose/idx17/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx17
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx18:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx18/etc:/opt/splunk/etc
      - /docker/dockercompose/idx18/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx18
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx19:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx19/etc:/opt/splunk/etc
      - /docker/dockercompose/idx19/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx19
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx20:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx20/etc:/opt/splunk/etc
      - /docker/dockercompose/idx20/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx20
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx21:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx21/etc:/opt/splunk/etc
      - /docker/dockercompose/idx21/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx21
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx22:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx22/etc:/opt/splunk/etc
      - /docker/dockercompose/idx22/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx22
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx23:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx23/etc:/opt/splunk/etc
      - /docker/dockercompose/idx23/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx23
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx24:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx24/etc:/opt/splunk/etc
      - /docker/dockercompose/idx24/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx24
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx25:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx25/etc:/opt/splunk/etc
      - /docker/dockercompose/idx25/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx25
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx26:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx26/etc:/opt/splunk/etc
      - /docker/dockercompose/idx26/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx26
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx27:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx27/etc:/opt/splunk/etc
      - /docker/dockercompose/idx27/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx27
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx28:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx28/etc:/opt/splunk/etc
      - /docker/dockercompose/idx28/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx28
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx29:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx29/etc:/opt/splunk/etc
      - /docker/dockercompose/idx29/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx29
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx30:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx30/etc:/opt/splunk/etc
      - /docker/dockercompose/idx30/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx30
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        
 
idx31:
    image: splunk/splunk:8.0
    volumes:
      - /docker/dockercompose/idx31/etc:/opt/splunk/etc
      - /docker/dockercompose/idx31/var:/opt/splunk/var
      - /docker/data/tickets/:/opt/splunk/var/lib/splunk/defaultdb/

    hostname: idx31
    environment:
     # - DEFAULTS_URL=http://splunk-defaults/default.yml
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Splunk4sidetesting
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_CLUSTER_MASTER_URL=clm
      - SPLUNK_IDXC_SECRET=mypass4splunk
      - DEBUG=true
      - SPLUNK_LICENSE_URI

        

