---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    dockerhosts:
      - docker-1
      - docker-2
      - docker-3
    ec2_region: "eu-central-1"
    route53_domain: "bwlab.de"

  become: false
  
  tasks:

    - name: get docker hosts information
      ec2_instance_facts:
        region: "{{ec2_region}}"
        filters:
          "tag:Name": docker-*
          instance-state-name: running
      register: docker_metadata

    # - name: debug
    #   debug:
    #     msg: "{{ docker_metadata.instances }}"

    - name:  set dns cname records
      route53:
          state: present
          zone: "{{ route53_domain }}" 
          record: "{{ item.tags.Name }}.{{ route53_domain }}"
          type: CNAME
          ttl: 60
          value:
            - "{{ item.public_dns_name }}" 
          wait: yes
          overwrite: true
      with_items:
        - "{{ docker_metadata.instances }}"
      loop_control:
        index_var: my_counter  