---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: dockerhosts
  vars:
    bucketfile: "tickets"

  tasks:

    - name: create docker folder
      file: 
        path: /home/ubuntu/.aws/
        state: directory 
        mode: 0744
      become: false

    - name: copy aws credentials
      copy: 
        src: /Users/andreas/.aws/credentials
        dest: /home/ubuntu/.aws/credentials
      become: false

    - name: checking if buckets.tar.gz exists
      stat: 
        path: /tmp/buckets.tar.gz
      register: buckets

    - name: Download files from S3
      aws_s3:
        mode: get
        bucket: "batchworks-tickets"
        object: "{{ bucketfile }}"
        dest: "/tmp/buckets.tar.gz"
      become: false
      when: buckets.stat.exists == false

    - name: Extract buckets.tar.gz into /var/lib/foo
      unarchive:
        remote_src: "yes"
        src: "/tmp/buckets.tar.gz"
        dest: /docker/data/
      when: buckets.stat.exists == false

    - name: give file permissions
      file: 
        path: /docker/data/tickets 
        state: directory 
        mode: 0777
        recurse: yes

    - name: remove aws credentials
      file:
        path: /home/ubuntu/.aws/credentials
        state: absent

